#!/usr/bin/env bash

#: exec_target = cli

## Initialize/reinstall site
##
## Usage: fin init-site

# Abort if anything fails
set -e

#-------------------------- Settings --------------------------------

# PROJECT_ROOT and DOCROOT are set as env variables in cli
SITE_DIRECTORY="default"
DOCROOT_PATH="${PROJECT_ROOT}/${DOCROOT}"
SRC_PATH="${PROJECT_ROOT}/src"
SITEDIR_PATH="${DOCROOT_PATH}/sites/${SITE_DIRECTORY}"

#-------------------------- END: Settings --------------------------------
#-------------------------- Functions --------------------------------

# Fix file/folder permissions
fix_permissions ()
{
	echo "Making site directory writable..."
	chmod 755 "${SITEDIR_PATH}"
}

# Install site
site_install ()
{
	cd $DOCROOT_PATH

  # TODO: Fix this to be done by a drupal scaffold customization.
  fin exec "cd /var/www/web; wget -O .htaccess http://cgit.drupalcode.org/drupal/plain/.htaccess?h=8.4.x"
	# We disable email sending here so site-install does not return an error
	PHP_OPTIONS="-d sendmail_path=`which true`" drupal site:install config_installer --langcode='en' --site-name='HFNY' --site-mail="alan.sherry@freeflowdigital.com" --account-name="admin" --account-mail="alan.sherry@freeflowdigital.com" --account-pass="admin"
}

#-------------------------- END: Functions --------------------------------

#-------------------------- Execution --------------------------------

# Project initialization steps
fix_permissions
time site_install

#-------------------------- END: Execution --------------------------------

